name: my_secret_variable
run-name: aprendiendo variables secretas
on: [workflow_dispatch]
jobs:
  secret_variable:
    runs-on: ubuntu-latest
    steps:
      - name: my_password
        run: echo "My secret password is ${{ secrets.PASSWORD }}"