name: my_secret_variable
run-name: aprendiendo variables secretas
on: [workflow_dispatch]
env:
  current_password: 12345      
jobs:
  secret_variable:
    runs-on: ubuntu-latest
    steps:
    - name: my_password
      run: |
        if [ ${{ secrets.PASSWORD }} == $current_password ]; then
          echo "The $current_password is my password!"
        else
          echo "$current_password not is my password"
        