name: my_secret_variable
run-name: aprendiendo variables secretas
on: [workflow_dispatch]
env:
  current_password: 12345      
jobs:
  secret_variable:
    if: ${{ '$secrets.PASSWORD' == '$current_password'}}
    runs-on: ubuntu-latest
    steps:
    - name: my_password
      run: echo "My password is ${{ env.current_password }} ${{ secrets.PASSWORD }}"
        