name: variables
run-name: aprendiendo variables
on: [workflow_dispatch]
env:
  local_variable: im a local variable
jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      job_variable: im from the job
    steps:
      - name: execute local variables
        env:
          step_variable: Im from step
        run: echo "we have 3 variables 1. $local_variable 2. $job_variable 3. $step_variable"
      - name: execute foreign variables
        run: echo "The foreign variable is ${{ vars.NAME_PLATZI_COURSE }}"